.wrapper {
  width: 450px;
  height: 707px;
  background-color: rgba(0, 0, 0, 0.6);
  border: 1px solid rgba(0, 0, 0, 0.6);
  border-radius:5px;
  padding: 48px 68px;
  justify-content: center;
  flex-direction: column;
}

.wrapper h1 {
text-align: left;
}

.wrapper form {
  display: flex;
  flex-direction: column;
}

.wrapper .input-box {
  position: relative;
  width: 100%;
  height: 50px;
  margin: 10px 0;

}
.input-box input{
  width: 100%;
  height: 100%;
  padding: 10px;
  background: rgba(223, 223, 223, 0.1);
  border: 1px solid rgba(255, 255, 255, 0.4);
  border-radius: 4px;
  outline: none;
  text-align: left;
  color: white;
  font-weight:500;

}

